version: '3'
services:
  nginx:
    container_name: mercado_nginx
    image: nginx:stable-alpine
    ports:
      - 3001:80
    depends_on:
      - node
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./containers/nginx:/var/log/nginx
    networks:
        - mercado-network
  node:
    container_name: mercado_node
    build: containers/node/.
    ports:
      #debug port
      - "9229:9229"   
    volumes:
      - ./containers/node/:/mercado/
      - ~/home/mercado/log:/mercado/node/log
    networks:
        - mercado-network
    working_dir: /mercado
    command: sh -c "npm install && pm2 start ecosystem.config.js --no-daemon"
    depends_on:
      - mongodb
      - postgresql
  postgresql:
    container_name: mercado_postgresql
    build: containers/postgresql/.
    ports:
      - "5432:5432"
    volumes:
      - ~/home/postgres/monitor/data:/var/lib/postgresql/data
    networks:
      - mercado-network
    tty: false
  mongodb:
    container_name: mercado_mongodb
    build: containers/mongodb/.
    #environment:
     # MONGO_INITDB_DATABASE: monitor
      #MONGO_INITDB_ROOT_USERNAME: monitor
      #MONGO_INITDB_ROOT_PASSWORD: monitor123!
    ports:
      - "27017:27017"
    volumes:
      #- ./containers/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ~/home/mongodb/mercado/data:/data/db
    networks:
      - mercado-network
networks:
  monitor-network:
    driver: bridge