version: '3'
services:
  container_name: mercado_nginx
    image: nginx:stable-alpine
    ports:
      - 3000:80
    depends_on:
      - node
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./containers/nginx:/var/log/nginx
    networks:
        - mercado-network
  node:
    container_name: mercado_node
    build: containers/node/.
    ports:
      #debug port
      - "9229:9229"   
    volumes:
      - ./containers/node/:/mercado/
      - ~/home/mercado/log:/mercado/node/log
    networks:
        - mercado-network
    working_dir: /mercado
    command: sh -c "npm install && pm2 start ecosystem.config.js --no-daemon"
    depends_on:
      - mongodb
  mongodb:
    container_name: mercado_mongodb
    build: containers/mongodb/.
    ports:
      - "27017:27017"
    volumes:
      #- ./containers/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ~/home/mongodb/mercado/data:/data/db
    networks:
      - mercado-network
networks:
  mercado-network:
    driver: bridge